common:
  setPVOwnerRef: true
classes:
  - name: rook-monitor
    hostDir: /data/local-static-provisioner/rook-ceph/monitor
    volumeMode: Filesystem
    fsType: ext4
    namePattern: "*"
    blockCleanerCommand:
    storageClass: true
