apiVersion: v1
kind: ConfigMap
metadata:
  name: hosts-configmap
data:
  known_hosts: |
    git.zjvis.org,10.5.24.47 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOqYw9C3dF6rRryWjUn1PwxXh4+LJaf/xrZvI9agiOWtc7ZNSCrf7Wo/QuEaBuS2Hd2mu6wlGWF9Jp6IS0+krL0=