
image:
  registry: localhost:5000/docker.io
  repository: bitnami/nginx
  tag: 1.21.3-debian-10-r29
  pullPolicy: IfNotPresent
  pullSecrets: []
extraVolumes:
  - name: nebula-ce-privatekey
    secret:
      secretName: nebula-ce-privatekey-secret
      items:
        - key: ssh-privatekey
          path: nebula_ce_privatekey
          mode: 0600
service:
  type: ClusterIP
cloneStaticSiteFromGit:
  image:
    registry: localhost:5000
    repository: docker.io/bitnami/git
    tag: 2.33.0-debian-10-r53
  enabled: true
  repository: git@git.zjvis.org:bigdata/nebula-ce.git
  branch: main
  interval: 60
  extraVolumeMounts:
    - name: nebula-ce-privatekey
      mountPath: /root/.ssh/
  extraEnvVars:
    - name: GIT_SSH_COMMAND
      value: "ssh -i /root/.ssh/nebula_ce_privatekey -F /dev/null -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hostname: my.nginx.tech
  path: /my-nginx-prefix(/|$)(.*)
  tls: false