service:
  type: NodePort
  port: 80
  httpsPort: 443
  targetPort:
    http: 8080
    https: 8443
  nodePorts:
    http: 32080
    https: 32443
cloneStaticSiteFromGit:
  enabled: true
  repository: https://github.com/yusanshui/blog
  branch: master