image:
  registry: localhost:5000
  repository: docker.io/bitnami/nginx
  tag: 1.21.3-debian-10-r29
  pullPolicy: IfNotPresent
  pullSecrets: []
service:
  type: ClusterIP
  port: 8080
extraVolumes:
  - name: nfs-pv
    persistentVolumeClaim:
      claimName: nfs-pvc
extraVolumeMounts:
  - name: nfs-pv
    mountPath: /usr/share/nginx/html
serverBlock: |-
  server {
    listen 8080;
    location / {
      root   /usr/share/nginx/html;
      autoindex on;
    }
  }
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  extraHosts:
    - name:
      path: /resources(/|$)(.*)
sidecars:
  - name: busybox
    image: localhost:5000/busybox:latest
    imagePullPolicy: Always
    command: ['sh', '-c', 'tail -f /etc/hosts']
    volumeMounts:
      - name: nfs-pv
        mountPath: "/root/data"