common:
  # Indicates if PVs should be dependents of the owner Node.
  setPVOwnerRef: true
classes:
  - name: local-disks # Defines name of storage classe.
    hostDir: /data/local-static-provisioner
    volumeMode: Filesystem
    fsType: ext4
    namePattern: "*"
    blockCleanerCommand:
      #  Do a quick reset of the block device during its cleanup.
      #  - "/scripts/quick_reset.sh"
      #  or use dd to zero out block dev in two iterations by uncommenting these lines
      #  - "/scripts/dd_zero.sh"
      #  - "2"
      # or run shred utility for 2 iteration.s
      - "/scripts/shred.sh"
      - "2"
    # Uncomment to create storage class object with default configuration.
    storageClass: true
      # Uncomment to create storage class object and configure it.
      # storageClass:
      # reclaimPolicy: Delete # Available reclaim policies: Delete/Retain, defaults: Delete.
    # isDefaultClass: true # set as default class