common:
  setPVOwnerRef: true
classes:
  - name: rook-data
    hostDir: /data/local-static-provisioner/rook-data
    volumeMode: Block
    fsType: ext4
    namePattern: "*"
    blockCleanerCommand:
      - "/scripts/shred.sh"
      - "2"
    storageClass: true
daemonset:
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
